package com.example.retrofittest.models;

import com.google.gson.annotations.SerializedName;

public class Post {

    private int userId;
    private int id;     //Gson ignores all fields that are null, so using Integer makes it null
    private String title;

    @SerializedName("body")
    private String content;

    public Post(int userId, String title, String content) {     //id is generated by retrofit
        this.userId = userId;
        this.title = title;
        this.content = content;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
}
